apiVersion: apps/v1
kind: Deployment
metadata:
   name: flaskapp-deployment
   labels:
     app: flaskapp

spec: #specification for deployment
  replicas: 1
  selector:
    matchLabels:
     app: flaskapp
  template:
    metadata:
     labels:
      app: flaskapp
    spec: #specification for pod
      containers:
       - name: flaskapp
         image: prashant887/flaskimage:1.0
         ports:
           - containerPort: 5000


#Connecting deployment to pod , set label to deployment line 6 , assoicate all pods to that label , which used by service   its a conn b/w service and deplyoment 
