apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"flaskapp"},"name":"flakapp-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"flaskapp"}},"template":{"metadata":{"labels":{"app":"flaskapp"}},"spec":{"containers":[{"image":"prashant887/flaskimage:1.0","name":"flaskapp","ports":[{"containerPort":5000}]}]}}}}
  creationTimestamp: "2021-08-16T09:21:34Z"
  generation: 1
  labels:
    app: flaskapp
  name: flakapp-deployment
  namespace: default
  resourceVersion: "390875"
  uid: 6d26f525-c757-43a1-83b2-ee8aca799279
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: flaskapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskapp
    spec:
      containers:
      - image: prashant887/flaskimage:1.0
        imagePullPolicy: IfNotPresent
        name: flaskapp
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-08-16T09:21:35Z"
    lastUpdateTime: "2021-08-16T09:21:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-08-16T09:21:34Z"
    lastUpdateTime: "2021-08-16T09:21:35Z"
    message: ReplicaSet "flakapp-deployment-66c4f57d9b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
