apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-reclaim
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 30Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/tmp/reclaim"


